# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
version: '1'
services:
  django-app:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - /Users/aldmikon/Desktop/Python_road/Projects/MoodyPlaylist:/app  # Adjust the paths accordingly
    environment:
      - DJANGO_LOG_LEVEL
      - SPOTIPY_CLIENT_ID
      - SPOTIPY_CLIENT_SECRET 
      - OPENWEATHER_API_KEY
    #develop:
     # watch:
        #- action: rebuild
        #  path: .


 



