version: '1'
services:
  django-app:
    build: 
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./logs:/app/logs # Adjust the paths accordingly
    environment:
      - DJANGO_LOG_LEVEL
      - SPOTIPY_CLIENT_ID
      - SPOTIPY_CLIENT_SECRET
      - SPOTIPY_REDIRECT_URI  
      - OPENWEATHER_API_KEY
      - CELERY_BROKER_URL
      - CELERY_RESULT_BACKEND
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: .
#Redis service 
  redis:
    image: redis
    ports:
      - 6379:6379
#Celery service
  celery:
    build: .
    command: celery -A config.tasks worker -l INFO
    volumes:
        - ./logs:/app/logs 
    environment:
        - CELERY_BROKER_URL
        - CELERY_RESULT_BACKEND
    depends_on:
        - django-app
        - redis

 



